---
- name: Include distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_os_family|lower }}.yml"

- name: Set facts
  include: facts.yml

- name: Install openjdk
  package: name="{{openjdk_package}}" state=present


- block:

    - name: generate keystore
      vars:
        key_password: "{{chronos_key_password}}"
        pkcs_password: "{{chronos_jks_password}}"
        jks_password: "{{chronos_jks_password}}"
      include: enable_ssl.yml

  when: chronos_enable_ssl|bool
  tags: chronos


- name: "Create chronos container env file"
  template:
    src={{chronosenv_template}} dest=/etc/chronos/.chronosenv


- name: run chronos container
  docker_container:
    name: chronos
    image: "{{ chronos_image }}"
    state: started
    detach: true
    restart_policy: always
    network_mode: host
    volumes:
    - "{{ chronos_keystore_path }}:{{ chronos_keystore_path }}"
    env_file: /etc/chronos/.chronosenv
  tags: chronos 
