---
- name: Set facts
  include: facts.yml

- name: Install openjdk
  apt: name="openjdk-7-jre-headless" state=present


- name: Check that the certificates exists
  stat: path=chronos.key
  register: chronos_key
- block:

    - name: generate keystore
      vars:
        key_password: "{{chronos_key_password}}"
        pkcs_password: "{{chronos_jks_password}}"
        jks_password: "{{chronos_jks_password}}"
      include: enable_ssl.yml

  when: chronos_key.stat.exists == False
  tags: chronos


- name: "Create marathon container env file"
  template:
    src={{chronosenv_template}} dest=/etc/marathon/.chronosenv


- name: run chronos container
  docker_container:
    name: chronos
    image: "{{ chronos_image }}"
    state: started
    detach: true
    restart_policy: always
    network_mode: host
    volumes:
    - "{{ chronos_keystore_path }}:{{ chronos_keystore_path }}"
    env_file: /etc/chronos/.chronosenv
  tags: chronos 
